# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zhangliwei/eppather-master/eppather

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zhangliwei/eppather-master/eppather

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zhangliwei/eppather-master/eppather/CMakeFiles /home/zhangliwei/eppather-master/eppather/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zhangliwei/eppather-master/eppather/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test-suite

# Build rule for target.
test-suite: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-suite
.PHONY : test-suite

# fast build rule for target.
test-suite/fast:
	$(MAKE) -f CMakeFiles/test-suite.dir/build.make CMakeFiles/test-suite.dir/build
.PHONY : test-suite/fast

#=============================================================================
# Target rules for targets named volce_tool

# Build rule for target.
volce_tool: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 volce_tool
.PHONY : volce_tool

# fast build rule for target.
volce_tool/fast:
	$(MAKE) -f CMakeFiles/volce_tool.dir/build.make CMakeFiles/volce_tool.dir/build
.PHONY : volce_tool/fast

#=============================================================================
# Target rules for targets named cnip

# Build rule for target.
cnip: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cnip
.PHONY : cnip

# fast build rule for target.
cnip/fast:
	$(MAKE) -f CMakeFiles/cnip.dir/build.make CMakeFiles/cnip.dir/build
.PHONY : cnip/fast

#=============================================================================
# Target rules for targets named psychecommon

# Build rule for target.
psychecommon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 psychecommon
.PHONY : psychecommon

# fast build rule for target.
psychecommon/fast:
	$(MAKE) -f common/CMakeFiles/psychecommon.dir/build.make common/CMakeFiles/psychecommon.dir/build
.PHONY : psychecommon/fast

#=============================================================================
# Target rules for targets named psychecfe

# Build rule for target.
psychecfe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 psychecfe
.PHONY : psychecfe

# fast build rule for target.
psychecfe/fast:
	$(MAKE) -f C/CMakeFiles/psychecfe.dir/build.make C/CMakeFiles/psychecfe.dir/build
.PHONY : psychecfe/fast

#=============================================================================
# Target rules for targets named psychecstd

# Build rule for target.
psychecstd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 psychecstd
.PHONY : psychecstd

# fast build rule for target.
psychecstd/fast:
	$(MAKE) -f C/stdlib-support/CMakeFiles/psychecstd.dir/build.make C/stdlib-support/CMakeFiles/psychecstd.dir/build
.PHONY : psychecstd/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) -f epat++/CMakeFiles/NightlyTest.dir/build.make epat++/CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) -f epat++/CMakeFiles/ContinuousConfigure.dir/build.make epat++/CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) -f epat++/CMakeFiles/ContinuousBuild.dir/build.make epat++/CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) -f epat++/CMakeFiles/NightlyConfigure.dir/build.make epat++/CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) -f epat++/CMakeFiles/NightlyMemoryCheck.dir/build.make epat++/CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) -f epat++/CMakeFiles/ExperimentalTest.dir/build.make epat++/CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) -f epat++/CMakeFiles/ContinuousUpdate.dir/build.make epat++/CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) -f epat++/CMakeFiles/NightlyUpdate.dir/build.make epat++/CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) -f epat++/CMakeFiles/ExperimentalMemCheck.dir/build.make epat++/CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) -f epat++/CMakeFiles/ExperimentalSubmit.dir/build.make epat++/CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) -f epat++/CMakeFiles/Experimental.dir/build.make epat++/CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) -f epat++/CMakeFiles/ContinuousCoverage.dir/build.make epat++/CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) -f epat++/CMakeFiles/ExperimentalConfigure.dir/build.make epat++/CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) -f epat++/CMakeFiles/Continuous.dir/build.make epat++/CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) -f epat++/CMakeFiles/Nightly.dir/build.make epat++/CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) -f epat++/CMakeFiles/NightlySubmit.dir/build.make epat++/CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) -f epat++/CMakeFiles/NightlyStart.dir/build.make epat++/CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) -f epat++/CMakeFiles/ExperimentalCoverage.dir/build.make epat++/CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) -f epat++/CMakeFiles/NightlyCoverage.dir/build.make epat++/CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) -f epat++/CMakeFiles/ExperimentalStart.dir/build.make epat++/CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) -f epat++/CMakeFiles/NightlyBuild.dir/build.make epat++/CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) -f epat++/CMakeFiles/ExperimentalBuild.dir/build.make epat++/CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) -f epat++/CMakeFiles/ExperimentalUpdate.dir/build.make epat++/CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) -f epat++/CMakeFiles/ContinuousStart.dir/build.make epat++/CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) -f epat++/CMakeFiles/ContinuousMemCheck.dir/build.make epat++/CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) -f epat++/CMakeFiles/ContinuousTest.dir/build.make epat++/CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) -f epat++/CMakeFiles/ContinuousSubmit.dir/build.make epat++/CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) -f epat++/CMakeFiles/NightlyMemCheck.dir/build.make epat++/CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named epat-protocol

# Build rule for target.
epat-protocol: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 epat-protocol
.PHONY : epat-protocol

# fast build rule for target.
epat-protocol/fast:
	$(MAKE) -f epat++/epat-protocol/CMakeFiles/epat-protocol.dir/build.make epat++/epat-protocol/CMakeFiles/epat-protocol.dir/build
.PHONY : epat-protocol/fast

#=============================================================================
# Target rules for targets named antlr4-runtime

# Build rule for target.
antlr4-runtime: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 antlr4-runtime
.PHONY : antlr4-runtime

# fast build rule for target.
antlr4-runtime/fast:
	$(MAKE) -f epat++/epat-protocol/grammar/antlr4-runtime/CMakeFiles/antlr4-runtime.dir/build.make epat++/epat-protocol/grammar/antlr4-runtime/CMakeFiles/antlr4-runtime.dir/build
.PHONY : antlr4-runtime/fast

#=============================================================================
# Target rules for targets named libepat++

# Build rule for target.
libepat++: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libepat++
.PHONY : libepat++

# fast build rule for target.
libepat++/fast:
	$(MAKE) -f epat++/libepat++/CMakeFiles/libepat++.dir/build.make epat++/libepat++/CMakeFiles/libepat++.dir/build
.PHONY : libepat++/fast

#=============================================================================
# Target rules for targets named epat-hello_world

# Build rule for target.
epat-hello_world: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 epat-hello_world
.PHONY : epat-hello_world

# fast build rule for target.
epat-hello_world/fast:
	$(MAKE) -f epat++/test/CMakeFiles/epat-hello_world.dir/build.make epat++/test/CMakeFiles/epat-hello_world.dir/build
.PHONY : epat-hello_world/fast

#=============================================================================
# Target rules for targets named epat-reg_test

# Build rule for target.
epat-reg_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 epat-reg_test
.PHONY : epat-reg_test

# fast build rule for target.
epat-reg_test/fast:
	$(MAKE) -f epat++/test/CMakeFiles/epat-reg_test.dir/build.make epat++/test/CMakeFiles/epat-reg_test.dir/build
.PHONY : epat-reg_test/fast

#=============================================================================
# Target rules for targets named epat-main

# Build rule for target.
epat-main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 epat-main
.PHONY : epat-main

# fast build rule for target.
epat-main/fast:
	$(MAKE) -f epat++/test/CMakeFiles/epat-main.dir/build.make epat++/test/CMakeFiles/epat-main.dir/build
.PHONY : epat-main/fast

#=============================================================================
# Target rules for targets named epat-cpath

# Build rule for target.
epat-cpath: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 epat-cpath
.PHONY : epat-cpath

# fast build rule for target.
epat-cpath/fast:
	$(MAKE) -f epat++/test/CMakeFiles/epat-cpath.dir/build.make epat++/test/CMakeFiles/epat-cpath.dir/build
.PHONY : epat-cpath/fast

#=============================================================================
# Target rules for targets named epat-array

# Build rule for target.
epat-array: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 epat-array
.PHONY : epat-array

# fast build rule for target.
epat-array/fast:
	$(MAKE) -f epat++/test/CMakeFiles/epat-array.dir/build.make epat++/test/CMakeFiles/epat-array.dir/build
.PHONY : epat-array/fast

TestSuiteRunner.o: TestSuiteRunner.cpp.o

.PHONY : TestSuiteRunner.o

# target to build an object file
TestSuiteRunner.cpp.o:
	$(MAKE) -f CMakeFiles/test-suite.dir/build.make CMakeFiles/test-suite.dir/TestSuiteRunner.cpp.o
.PHONY : TestSuiteRunner.cpp.o

TestSuiteRunner.i: TestSuiteRunner.cpp.i

.PHONY : TestSuiteRunner.i

# target to preprocess a source file
TestSuiteRunner.cpp.i:
	$(MAKE) -f CMakeFiles/test-suite.dir/build.make CMakeFiles/test-suite.dir/TestSuiteRunner.cpp.i
.PHONY : TestSuiteRunner.cpp.i

TestSuiteRunner.s: TestSuiteRunner.cpp.s

.PHONY : TestSuiteRunner.s

# target to generate assembly for a file
TestSuiteRunner.cpp.s:
	$(MAKE) -f CMakeFiles/test-suite.dir/build.make CMakeFiles/test-suite.dir/TestSuiteRunner.cpp.s
.PHONY : TestSuiteRunner.cpp.s

cnippet/CompilerFrontend.o: cnippet/CompilerFrontend.cpp.o

.PHONY : cnippet/CompilerFrontend.o

# target to build an object file
cnippet/CompilerFrontend.cpp.o:
	$(MAKE) -f CMakeFiles/cnip.dir/build.make CMakeFiles/cnip.dir/cnippet/CompilerFrontend.cpp.o
.PHONY : cnippet/CompilerFrontend.cpp.o

cnippet/CompilerFrontend.i: cnippet/CompilerFrontend.cpp.i

.PHONY : cnippet/CompilerFrontend.i

# target to preprocess a source file
cnippet/CompilerFrontend.cpp.i:
	$(MAKE) -f CMakeFiles/cnip.dir/build.make CMakeFiles/cnip.dir/cnippet/CompilerFrontend.cpp.i
.PHONY : cnippet/CompilerFrontend.cpp.i

cnippet/CompilerFrontend.s: cnippet/CompilerFrontend.cpp.s

.PHONY : cnippet/CompilerFrontend.s

# target to generate assembly for a file
cnippet/CompilerFrontend.cpp.s:
	$(MAKE) -f CMakeFiles/cnip.dir/build.make CMakeFiles/cnip.dir/cnippet/CompilerFrontend.cpp.s
.PHONY : cnippet/CompilerFrontend.cpp.s

cnippet/CompilerFrontend_C.o: cnippet/CompilerFrontend_C.cpp.o

.PHONY : cnippet/CompilerFrontend_C.o

# target to build an object file
cnippet/CompilerFrontend_C.cpp.o:
	$(MAKE) -f CMakeFiles/cnip.dir/build.make CMakeFiles/cnip.dir/cnippet/CompilerFrontend_C.cpp.o
.PHONY : cnippet/CompilerFrontend_C.cpp.o

cnippet/CompilerFrontend_C.i: cnippet/CompilerFrontend_C.cpp.i

.PHONY : cnippet/CompilerFrontend_C.i

# target to preprocess a source file
cnippet/CompilerFrontend_C.cpp.i:
	$(MAKE) -f CMakeFiles/cnip.dir/build.make CMakeFiles/cnip.dir/cnippet/CompilerFrontend_C.cpp.i
.PHONY : cnippet/CompilerFrontend_C.cpp.i

cnippet/CompilerFrontend_C.s: cnippet/CompilerFrontend_C.cpp.s

.PHONY : cnippet/CompilerFrontend_C.s

# target to generate assembly for a file
cnippet/CompilerFrontend_C.cpp.s:
	$(MAKE) -f CMakeFiles/cnip.dir/build.make CMakeFiles/cnip.dir/cnippet/CompilerFrontend_C.cpp.s
.PHONY : cnippet/CompilerFrontend_C.cpp.s

cnippet/Configuration.o: cnippet/Configuration.cpp.o

.PHONY : cnippet/Configuration.o

# target to build an object file
cnippet/Configuration.cpp.o:
	$(MAKE) -f CMakeFiles/cnip.dir/build.make CMakeFiles/cnip.dir/cnippet/Configuration.cpp.o
.PHONY : cnippet/Configuration.cpp.o

cnippet/Configuration.i: cnippet/Configuration.cpp.i

.PHONY : cnippet/Configuration.i

# target to preprocess a source file
cnippet/Configuration.cpp.i:
	$(MAKE) -f CMakeFiles/cnip.dir/build.make CMakeFiles/cnip.dir/cnippet/Configuration.cpp.i
.PHONY : cnippet/Configuration.cpp.i

cnippet/Configuration.s: cnippet/Configuration.cpp.s

.PHONY : cnippet/Configuration.s

# target to generate assembly for a file
cnippet/Configuration.cpp.s:
	$(MAKE) -f CMakeFiles/cnip.dir/build.make CMakeFiles/cnip.dir/cnippet/Configuration.cpp.s
.PHONY : cnippet/Configuration.cpp.s

cnippet/Configuration_C.o: cnippet/Configuration_C.cpp.o

.PHONY : cnippet/Configuration_C.o

# target to build an object file
cnippet/Configuration_C.cpp.o:
	$(MAKE) -f CMakeFiles/cnip.dir/build.make CMakeFiles/cnip.dir/cnippet/Configuration_C.cpp.o
.PHONY : cnippet/Configuration_C.cpp.o

cnippet/Configuration_C.i: cnippet/Configuration_C.cpp.i

.PHONY : cnippet/Configuration_C.i

# target to preprocess a source file
cnippet/Configuration_C.cpp.i:
	$(MAKE) -f CMakeFiles/cnip.dir/build.make CMakeFiles/cnip.dir/cnippet/Configuration_C.cpp.i
.PHONY : cnippet/Configuration_C.cpp.i

cnippet/Configuration_C.s: cnippet/Configuration_C.cpp.s

.PHONY : cnippet/Configuration_C.s

# target to generate assembly for a file
cnippet/Configuration_C.cpp.s:
	$(MAKE) -f CMakeFiles/cnip.dir/build.make CMakeFiles/cnip.dir/cnippet/Configuration_C.cpp.s
.PHONY : cnippet/Configuration_C.cpp.s

cnippet/Driver.o: cnippet/Driver.cpp.o

.PHONY : cnippet/Driver.o

# target to build an object file
cnippet/Driver.cpp.o:
	$(MAKE) -f CMakeFiles/cnip.dir/build.make CMakeFiles/cnip.dir/cnippet/Driver.cpp.o
.PHONY : cnippet/Driver.cpp.o

cnippet/Driver.i: cnippet/Driver.cpp.i

.PHONY : cnippet/Driver.i

# target to preprocess a source file
cnippet/Driver.cpp.i:
	$(MAKE) -f CMakeFiles/cnip.dir/build.make CMakeFiles/cnip.dir/cnippet/Driver.cpp.i
.PHONY : cnippet/Driver.cpp.i

cnippet/Driver.s: cnippet/Driver.cpp.s

.PHONY : cnippet/Driver.s

# target to generate assembly for a file
cnippet/Driver.cpp.s:
	$(MAKE) -f CMakeFiles/cnip.dir/build.make CMakeFiles/cnip.dir/cnippet/Driver.cpp.s
.PHONY : cnippet/Driver.cpp.s

cnippet/Main.o: cnippet/Main.cpp.o

.PHONY : cnippet/Main.o

# target to build an object file
cnippet/Main.cpp.o:
	$(MAKE) -f CMakeFiles/cnip.dir/build.make CMakeFiles/cnip.dir/cnippet/Main.cpp.o
.PHONY : cnippet/Main.cpp.o

cnippet/Main.i: cnippet/Main.cpp.i

.PHONY : cnippet/Main.i

# target to preprocess a source file
cnippet/Main.cpp.i:
	$(MAKE) -f CMakeFiles/cnip.dir/build.make CMakeFiles/cnip.dir/cnippet/Main.cpp.i
.PHONY : cnippet/Main.cpp.i

cnippet/Main.s: cnippet/Main.cpp.s

.PHONY : cnippet/Main.s

# target to generate assembly for a file
cnippet/Main.cpp.s:
	$(MAKE) -f CMakeFiles/cnip.dir/build.make CMakeFiles/cnip.dir/cnippet/Main.cpp.s
.PHONY : cnippet/Main.cpp.s

cnippet/Plugin.o: cnippet/Plugin.cpp.o

.PHONY : cnippet/Plugin.o

# target to build an object file
cnippet/Plugin.cpp.o:
	$(MAKE) -f CMakeFiles/cnip.dir/build.make CMakeFiles/cnip.dir/cnippet/Plugin.cpp.o
.PHONY : cnippet/Plugin.cpp.o

cnippet/Plugin.i: cnippet/Plugin.cpp.i

.PHONY : cnippet/Plugin.i

# target to preprocess a source file
cnippet/Plugin.cpp.i:
	$(MAKE) -f CMakeFiles/cnip.dir/build.make CMakeFiles/cnip.dir/cnippet/Plugin.cpp.i
.PHONY : cnippet/Plugin.cpp.i

cnippet/Plugin.s: cnippet/Plugin.cpp.s

.PHONY : cnippet/Plugin.s

# target to generate assembly for a file
cnippet/Plugin.cpp.s:
	$(MAKE) -f CMakeFiles/cnip.dir/build.make CMakeFiles/cnip.dir/cnippet/Plugin.cpp.s
.PHONY : cnippet/Plugin.cpp.s

data-types/Substitution.o: data-types/Substitution.cpp.o

.PHONY : data-types/Substitution.o

# target to build an object file
data-types/Substitution.cpp.o:
	$(MAKE) -f CMakeFiles/cnip.dir/build.make CMakeFiles/cnip.dir/data-types/Substitution.cpp.o
.PHONY : data-types/Substitution.cpp.o

data-types/Substitution.i: data-types/Substitution.cpp.i

.PHONY : data-types/Substitution.i

# target to preprocess a source file
data-types/Substitution.cpp.i:
	$(MAKE) -f CMakeFiles/cnip.dir/build.make CMakeFiles/cnip.dir/data-types/Substitution.cpp.i
.PHONY : data-types/Substitution.cpp.i

data-types/Substitution.s: data-types/Substitution.cpp.s

.PHONY : data-types/Substitution.s

# target to generate assembly for a file
data-types/Substitution.cpp.s:
	$(MAKE) -f CMakeFiles/cnip.dir/build.make CMakeFiles/cnip.dir/data-types/Substitution.cpp.s
.PHONY : data-types/Substitution.cpp.s

tests/TestSuite.o: tests/TestSuite.cpp.o

.PHONY : tests/TestSuite.o

# target to build an object file
tests/TestSuite.cpp.o:
	$(MAKE) -f CMakeFiles/test-suite.dir/build.make CMakeFiles/test-suite.dir/tests/TestSuite.cpp.o
.PHONY : tests/TestSuite.cpp.o

tests/TestSuite.i: tests/TestSuite.cpp.i

.PHONY : tests/TestSuite.i

# target to preprocess a source file
tests/TestSuite.cpp.i:
	$(MAKE) -f CMakeFiles/test-suite.dir/build.make CMakeFiles/test-suite.dir/tests/TestSuite.cpp.i
.PHONY : tests/TestSuite.cpp.i

tests/TestSuite.s: tests/TestSuite.cpp.s

.PHONY : tests/TestSuite.s

# target to generate assembly for a file
tests/TestSuite.cpp.s:
	$(MAKE) -f CMakeFiles/test-suite.dir/build.make CMakeFiles/test-suite.dir/tests/TestSuite.cpp.s
.PHONY : tests/TestSuite.cpp.s

tools/GnuCompilerFacade.o: tools/GnuCompilerFacade.cpp.o

.PHONY : tools/GnuCompilerFacade.o

# target to build an object file
tools/GnuCompilerFacade.cpp.o:
	$(MAKE) -f CMakeFiles/cnip.dir/build.make CMakeFiles/cnip.dir/tools/GnuCompilerFacade.cpp.o
.PHONY : tools/GnuCompilerFacade.cpp.o

tools/GnuCompilerFacade.i: tools/GnuCompilerFacade.cpp.i

.PHONY : tools/GnuCompilerFacade.i

# target to preprocess a source file
tools/GnuCompilerFacade.cpp.i:
	$(MAKE) -f CMakeFiles/cnip.dir/build.make CMakeFiles/cnip.dir/tools/GnuCompilerFacade.cpp.i
.PHONY : tools/GnuCompilerFacade.cpp.i

tools/GnuCompilerFacade.s: tools/GnuCompilerFacade.cpp.s

.PHONY : tools/GnuCompilerFacade.s

# target to generate assembly for a file
tools/GnuCompilerFacade.cpp.s:
	$(MAKE) -f CMakeFiles/cnip.dir/build.make CMakeFiles/cnip.dir/tools/GnuCompilerFacade.cpp.s
.PHONY : tools/GnuCompilerFacade.cpp.s

utility/FileInfo.o: utility/FileInfo.cpp.o

.PHONY : utility/FileInfo.o

# target to build an object file
utility/FileInfo.cpp.o:
	$(MAKE) -f CMakeFiles/cnip.dir/build.make CMakeFiles/cnip.dir/utility/FileInfo.cpp.o
.PHONY : utility/FileInfo.cpp.o

utility/FileInfo.i: utility/FileInfo.cpp.i

.PHONY : utility/FileInfo.i

# target to preprocess a source file
utility/FileInfo.cpp.i:
	$(MAKE) -f CMakeFiles/cnip.dir/build.make CMakeFiles/cnip.dir/utility/FileInfo.cpp.i
.PHONY : utility/FileInfo.cpp.i

utility/FileInfo.s: utility/FileInfo.cpp.s

.PHONY : utility/FileInfo.s

# target to generate assembly for a file
utility/FileInfo.cpp.s:
	$(MAKE) -f CMakeFiles/cnip.dir/build.make CMakeFiles/cnip.dir/utility/FileInfo.cpp.s
.PHONY : utility/FileInfo.cpp.s

utility/IO.o: utility/IO.cpp.o

.PHONY : utility/IO.o

# target to build an object file
utility/IO.cpp.o:
	$(MAKE) -f CMakeFiles/cnip.dir/build.make CMakeFiles/cnip.dir/utility/IO.cpp.o
.PHONY : utility/IO.cpp.o

utility/IO.i: utility/IO.cpp.i

.PHONY : utility/IO.i

# target to preprocess a source file
utility/IO.cpp.i:
	$(MAKE) -f CMakeFiles/cnip.dir/build.make CMakeFiles/cnip.dir/utility/IO.cpp.i
.PHONY : utility/IO.cpp.i

utility/IO.s: utility/IO.cpp.s

.PHONY : utility/IO.s

# target to generate assembly for a file
utility/IO.cpp.s:
	$(MAKE) -f CMakeFiles/cnip.dir/build.make CMakeFiles/cnip.dir/utility/IO.cpp.s
.PHONY : utility/IO.cpp.s

utility/Process.o: utility/Process.cpp.o

.PHONY : utility/Process.o

# target to build an object file
utility/Process.cpp.o:
	$(MAKE) -f CMakeFiles/cnip.dir/build.make CMakeFiles/cnip.dir/utility/Process.cpp.o
.PHONY : utility/Process.cpp.o

utility/Process.i: utility/Process.cpp.i

.PHONY : utility/Process.i

# target to preprocess a source file
utility/Process.cpp.i:
	$(MAKE) -f CMakeFiles/cnip.dir/build.make CMakeFiles/cnip.dir/utility/Process.cpp.i
.PHONY : utility/Process.cpp.i

utility/Process.s: utility/Process.cpp.s

.PHONY : utility/Process.s

# target to generate assembly for a file
utility/Process.cpp.s:
	$(MAKE) -f CMakeFiles/cnip.dir/build.make CMakeFiles/cnip.dir/utility/Process.cpp.s
.PHONY : utility/Process.cpp.s

volce/main.o: volce/main.cpp.o

.PHONY : volce/main.o

# target to build an object file
volce/main.cpp.o:
	$(MAKE) -f CMakeFiles/volce_tool.dir/build.make CMakeFiles/volce_tool.dir/volce/main.cpp.o
.PHONY : volce/main.cpp.o

volce/main.i: volce/main.cpp.i

.PHONY : volce/main.i

# target to preprocess a source file
volce/main.cpp.i:
	$(MAKE) -f CMakeFiles/volce_tool.dir/build.make CMakeFiles/volce_tool.dir/volce/main.cpp.i
.PHONY : volce/main.cpp.i

volce/main.s: volce/main.cpp.s

.PHONY : volce/main.s

# target to generate assembly for a file
volce/main.cpp.s:
	$(MAKE) -f CMakeFiles/volce_tool.dir/build.make CMakeFiles/volce_tool.dir/volce/main.cpp.s
.PHONY : volce/main.cpp.s

volce/volce_api.o: volce/volce_api.cpp.o

.PHONY : volce/volce_api.o

# target to build an object file
volce/volce_api.cpp.o:
	$(MAKE) -f CMakeFiles/volce_tool.dir/build.make CMakeFiles/volce_tool.dir/volce/volce_api.cpp.o
	$(MAKE) -f CMakeFiles/cnip.dir/build.make CMakeFiles/cnip.dir/volce/volce_api.cpp.o
.PHONY : volce/volce_api.cpp.o

volce/volce_api.i: volce/volce_api.cpp.i

.PHONY : volce/volce_api.i

# target to preprocess a source file
volce/volce_api.cpp.i:
	$(MAKE) -f CMakeFiles/volce_tool.dir/build.make CMakeFiles/volce_tool.dir/volce/volce_api.cpp.i
	$(MAKE) -f CMakeFiles/cnip.dir/build.make CMakeFiles/cnip.dir/volce/volce_api.cpp.i
.PHONY : volce/volce_api.cpp.i

volce/volce_api.s: volce/volce_api.cpp.s

.PHONY : volce/volce_api.s

# target to generate assembly for a file
volce/volce_api.cpp.s:
	$(MAKE) -f CMakeFiles/volce_tool.dir/build.make CMakeFiles/volce_tool.dir/volce/volce_api.cpp.s
	$(MAKE) -f CMakeFiles/cnip.dir/build.make CMakeFiles/cnip.dir/volce/volce_api.cpp.s
.PHONY : volce/volce_api.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test-suite"
	@echo "... install/local"
	@echo "... volce_tool"
	@echo "... cnip"
	@echo "... psychecommon"
	@echo "... psychecfe"
	@echo "... psychecstd"
	@echo "... NightlyTest"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyMemoryCheck"
	@echo "... ExperimentalTest"
	@echo "... ContinuousUpdate"
	@echo "... NightlyUpdate"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalSubmit"
	@echo "... Experimental"
	@echo "... ContinuousCoverage"
	@echo "... ExperimentalConfigure"
	@echo "... Continuous"
	@echo "... Nightly"
	@echo "... NightlySubmit"
	@echo "... NightlyStart"
	@echo "... ExperimentalCoverage"
	@echo "... NightlyCoverage"
	@echo "... ExperimentalStart"
	@echo "... NightlyBuild"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalUpdate"
	@echo "... ContinuousStart"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousTest"
	@echo "... ContinuousSubmit"
	@echo "... NightlyMemCheck"
	@echo "... epat-protocol"
	@echo "... antlr4-runtime"
	@echo "... libepat++"
	@echo "... epat-hello_world"
	@echo "... epat-reg_test"
	@echo "... epat-main"
	@echo "... epat-cpath"
	@echo "... epat-array"
	@echo "... TestSuiteRunner.o"
	@echo "... TestSuiteRunner.i"
	@echo "... TestSuiteRunner.s"
	@echo "... cnippet/CompilerFrontend.o"
	@echo "... cnippet/CompilerFrontend.i"
	@echo "... cnippet/CompilerFrontend.s"
	@echo "... cnippet/CompilerFrontend_C.o"
	@echo "... cnippet/CompilerFrontend_C.i"
	@echo "... cnippet/CompilerFrontend_C.s"
	@echo "... cnippet/Configuration.o"
	@echo "... cnippet/Configuration.i"
	@echo "... cnippet/Configuration.s"
	@echo "... cnippet/Configuration_C.o"
	@echo "... cnippet/Configuration_C.i"
	@echo "... cnippet/Configuration_C.s"
	@echo "... cnippet/Driver.o"
	@echo "... cnippet/Driver.i"
	@echo "... cnippet/Driver.s"
	@echo "... cnippet/Main.o"
	@echo "... cnippet/Main.i"
	@echo "... cnippet/Main.s"
	@echo "... cnippet/Plugin.o"
	@echo "... cnippet/Plugin.i"
	@echo "... cnippet/Plugin.s"
	@echo "... data-types/Substitution.o"
	@echo "... data-types/Substitution.i"
	@echo "... data-types/Substitution.s"
	@echo "... tests/TestSuite.o"
	@echo "... tests/TestSuite.i"
	@echo "... tests/TestSuite.s"
	@echo "... tools/GnuCompilerFacade.o"
	@echo "... tools/GnuCompilerFacade.i"
	@echo "... tools/GnuCompilerFacade.s"
	@echo "... utility/FileInfo.o"
	@echo "... utility/FileInfo.i"
	@echo "... utility/FileInfo.s"
	@echo "... utility/IO.o"
	@echo "... utility/IO.i"
	@echo "... utility/IO.s"
	@echo "... utility/Process.o"
	@echo "... utility/Process.i"
	@echo "... utility/Process.s"
	@echo "... volce/main.o"
	@echo "... volce/main.i"
	@echo "... volce/main.s"
	@echo "... volce/volce_api.o"
	@echo "... volce/volce_api.i"
	@echo "... volce/volce_api.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

